// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "Payback";
inline constexpr char kVersion[] = "1.4.1";
inline constexpr std::int64_t kBuild = 8;
inline constexpr char kIdentifier[] = "site.jrtx.payback";
inline constexpr char kReleaseChannel[] = "stable";

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_Bytes(rivet::Bytes const& v) { return rivet::Value(v); }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Void() { return rivet::Value{}; }

inline rivet::Bytes decode_Bytes(rivet::Value const& v) { if (auto p = std::get_if<rivet::Bytes>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bytes"); }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
}  // namespace detail

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<rivet::Bytes> activate_license(rivet::Bytes payload) { auto raw = backend_.call("activate-license", rivet::Value::List{detail::encode_Bytes(payload)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t activate_license_async(rivet::Bytes payload, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("activate-license", rivet::Value::List{detail::encode_Bytes(payload)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> add_device(rivet::Bytes payload) { auto raw = backend_.call("add-device", rivet::Value::List{detail::encode_Bytes(payload)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t add_device_async(rivet::Bytes payload, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("add-device", rivet::Value::List{detail::encode_Bytes(payload)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> check_updates(bool force) { auto raw = backend_.call("check-updates", rivet::Value::List{detail::encode_Bool(force)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t check_updates_async(bool force, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("check-updates", rivet::Value::List{detail::encode_Bool(force)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> daily_digest() { auto raw = backend_.call("daily-digest", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t daily_digest_async(std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("daily-digest", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> delete_device(std::string id) { auto raw = backend_.call("delete-device", rivet::Value::List{detail::encode_String(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t delete_device_async(std::string id, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("delete-device", rivet::Value::List{detail::encode_String(id)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> license_state() { auto raw = backend_.call("license-state", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t license_state_async(std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("license-state", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> load_all() { auto raw = backend_.call("load-all", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t load_all_async(std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("load-all", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> save_settings(rivet::Bytes payload) { auto raw = backend_.call("save-settings", rivet::Value::List{detail::encode_Bytes(payload)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_settings_async(rivet::Bytes payload, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-settings", rivet::Value::List{detail::encode_Bytes(payload)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> start_download() { auto raw = backend_.call("start-download", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t start_download_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("start-download", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> update_device(rivet::Bytes payload) { auto raw = backend_.call("update-device", rivet::Value::List{detail::encode_Bytes(payload)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_device_async(rivet::Bytes payload, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-device", rivet::Value::List{detail::encode_Bytes(payload)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> update_state() { auto raw = backend_.call("update-state", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_state_async(std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-state", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
