// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "Payback"
    public static let version = "1.4.1"
    public static let build: Int64 = 8
    public static let identifier = "site.jrtx.payback"
    public static let releaseChannel = "stable"
}

private func encode_Bytes(_ v: Data) -> RivetValue { .bytes(v) }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode_Void(_ v: Void) -> RivetValue { .null }

private func decode_Bytes(_ v: RivetValue) throws -> Data { guard case .bytes(let x) = v else { throw RivetGeneratedError.typeMismatch("Bytes") }; return x }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func activate_license(payload: Data) async throws -> Data {
        let result = try await client.call("activate-license", arguments: [encode_Bytes(payload)])
        return try decode_Bytes(result)
    }
    public func add_device(payload: Data) async throws -> Data {
        let result = try await client.call("add-device", arguments: [encode_Bytes(payload)])
        return try decode_Bytes(result)
    }
    public func check_updates(force: Bool) async throws -> Data {
        let result = try await client.call("check-updates", arguments: [encode_Bool(force)])
        return try decode_Bytes(result)
    }
    public func daily_digest() async throws -> Data {
        let result = try await client.call("daily-digest", arguments: [])
        return try decode_Bytes(result)
    }
    public func delete_device(id: String) async throws -> Void {
        let result = try await client.call("delete-device", arguments: [encode_String(id)])
        return try decode_Void(result)
    }
    public func license_state() async throws -> Data {
        let result = try await client.call("license-state", arguments: [])
        return try decode_Bytes(result)
    }
    public func load_all() async throws -> Data {
        let result = try await client.call("load-all", arguments: [])
        return try decode_Bytes(result)
    }
    public func save_settings(payload: Data) async throws -> Data {
        let result = try await client.call("save-settings", arguments: [encode_Bytes(payload)])
        return try decode_Bytes(result)
    }
    public func start_download() async throws -> Void {
        let result = try await client.call("start-download", arguments: [])
        return try decode_Void(result)
    }
    public func update_device(payload: Data) async throws -> Data {
        let result = try await client.call("update-device", arguments: [encode_Bytes(payload)])
        return try decode_Bytes(result)
    }
    public func update_state() async throws -> Data {
        let result = try await client.call("update-state", arguments: [])
        return try decode_Bytes(result)
    }
}
