#lang racket/base

;; Release identity duplicated from rivet.rktd. The packaged app cannot read
;; the project file at runtime, so the updater embeds these constants. Keep
;; them in sync with rivet.rktd (AGENTS.md lists this as a release checklist
;; item).

(provide app-version
         app-build
         app-identifier
         app-channel
         app-display-name
         update-key-id
         update-public-key-b64
         default-update-base-url)

(define app-version "1.1.1")
(define app-build 4)
(define app-identifier "site.jrtx.payback")
(define app-channel 'stable)
(define app-display-name "Payback")

(define update-key-id "payback-2026-09")

;; SubjectPublicKeyInfo DER, base64. Generated by scripts/gen-update-keys.
;; Rotate by shipping a build that trusts the next key before signing
;; releases exclusively with it (docs/updates.md).
(define update-public-key-b64
  "MCowBQYDK2VwAyEANWBRj25Bl7lr9kGL19Um7TYiZ6Ap7ed1iCOC1SgQAtM=")

(define default-update-base-url
  "https://github.com/turinglambdaai/payback/releases/latest/download")
